// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjUs6bpxiJJLmZZtCGKC1dOWeBiZedlHc',
    appId: '1:842658772918:web:a57b4f493ec2864f4fb317',
    messagingSenderId: '842658772918',
    projectId: 'e-mart-2ef4a',
    authDomain: 'e-mart-2ef4a.firebaseapp.com',
    storageBucket: 'e-mart-2ef4a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKeByfr4BST49PCyRsfjkXXY5daHWUiqA',
    appId: '1:842658772918:android:338813d00da49e734fb317',
    messagingSenderId: '842658772918',
    projectId: 'e-mart-2ef4a',
    storageBucket: 'e-mart-2ef4a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIttVjM9AiqlZdxndGob6EWZ6uFx0_I5U',
    appId: '1:842658772918:ios:15c35399a7bda0124fb317',
    messagingSenderId: '842658772918',
    projectId: 'e-mart-2ef4a',
    storageBucket: 'e-mart-2ef4a.appspot.com',
    iosClientId: '842658772918-4ln57j5rgdkjb4adunuv19q1690l8psl.apps.googleusercontent.com',
    iosBundleId: 'com.example.eMart',
  );
}
